import { createI18n } from "vue-i18n";

export const lang = {
  en: {
    login: {
      quote: "«Any big goal starts with one small task.»",
      hint: "Keep track of things as naturally as a plant grows - step by step, day by day.",
      password: "Password",
      logInButton: "Log In",
      hint2: "First time here?",
      linkRegis: "Create account",
      welcomeBack: "Welcome back",
      hint3: "Log in to continue care for your tasks.",
    },
    register: {
      title: "Register",
      hint1: "Register to start caring for your tasks.",
      name: "Name",
      namePlaceholder: "Sprouty",
      repeatPassword: "Repeat password",
      hint2: "Already in a team?",
      linkLogin: "Log in!",
      buttonRegis: "Create",
    },
    errors: {
      errorNoData: "please, write your data",
      errorPasswordMatch: "passwords do not match",
      errorPasswordValid: "password must be at least 6 symbols",
      errorUsernameTaken: "this username is taken",
      errorUsernameValid: "usersname must be at least 2 symbols",
      errorNoSuchAcc: "no such account or wrong password",
    },
    sideBar: {
      search: "Find task",
      homepage: "Homepage",
      calendar: "Calendar",
      categories: {
        title: "Categories",
        work: "work",
        personal: "personal",
        study: "study",
        addCategory: "Add category",
        newCatName: "category name",
      },
    },
    taskManager: {
      greeting: "Hello, ",
      tasksForToday: "tasks for today",
      addTaskInput: "what will you plant today?",
      addTaskButton: "add +",
      filterToday: "today",
      filterAll: "all",
      filterActive: "active",
      filterDone: "done",
      filterDeadlined: "deadlined",
      tasks: "tasks",
      titleAllTasks: "All tasks",
      titleActiveTasks: "Active tasks",
      titleDoneTasks: "Done tasks",
      titleTodayTasks: "Today tasks",
      titleDeadlinedTasks: "Deadlined tasks",
      noTasksMessage: "No tasks found 🌱",
      deleteAllDoneTasksButton: "delete done",
      col1: "Status",
      col2: "Task",
      col3: "Category",
      col5: "Delete",
      switcherTable: "Switch to table",
      switcherGrid: "Switch to grid",
      deadlineDate: "Deadline",
      createDate: "Created",
      doneDate: "Done date",
      daysLeft: "days left:",
      deadlinedDays: "deadlined for ",
      days: "days",
      more: "more...",
    },
    settings: {
      title: "Settings",
      profile: "PROFILE",
      hint1: "Click on the photo to upload a new one",
      name: "Name",
      save: "Save changes",
      styling: "STYLING",
      light: "Light",
      dark: "Dark",
      account: "ACCOUNT",
      exitAcc: "Log out of account",
      hint2: "You will need to log in again to see your tasks.",
      exit: "Log out",
    },
    weather: {
      code1: "Clear",
      code2: "Partly cloudy",
      code3: "Foggy",
      code4: "Rainy",
      code5: "Snowy",
      code6: "Heavy rain",
      code7: "Cloudy",
      loading: "Weather loading...",
      title1: "Bishkek",
      title2: "temperature: ",
      title3: "outside: ",
      error:'No forecast'
    },
    calendar: {
      chosenDay: 'CHOSEN DAY',
    }
  },
  ru: {
    login: {
      quote: "«Любая большая цель начинается с одной маленькой задачи.»",
      hint: "Отслеживайте дела так же естественно, как растёт растение — шаг за шагом, день за днём.",
      password: "Пароль",
      logInButton: "Войти",
      hint2: "Впервые здесь?",
      linkRegis: "Создать аккаунт",
      welcomeBack: "С возвращением",
      hint3: "Войдите, чтобы продолжить ухаживать за своими задачами.",
    },
    register: {
      title: "Регистрация",
      hint1: "Зарегистрируйтесь, чтобы начать ухаживать за своими задачами.",
      name: "Имя",
      namePlaceholder: "Спрути",
      repeatPassword: "Повторить пароль",
      hint2: "Уже в команде?",
      linkLogin: "Войти!",
      buttonRegis: "Создать",
    },

    errors: {
      errorNoData: "пожалуйста, заполните поля",
      errorPasswordMatch: "пароли не совпадают",
      errorPasswordValid: "пароль дожен быть минимум из 6 символов",
      errorUsernameTaken: "этот никнейм занят",
      errorUsernameValid: "никнейм должен быть минимум из 2 символов",
      errorNoSuchAcc: "пользователь не найден или неверный пароль",
    },
    sideBar: {
      search: "Найти задачу",
      homepage: "Главная",
      calendar: "Календарь",
      categories: {
        title: "Категории",
        work: "работа",
        personal: "личное",
        study: "учеба",
        addCategory: "Добавить категорию",
        newCatName: "назови категорию",
      },
    },
    taskManager: {
      greeting: "Привет, ",
      tasksForToday: "задачи на сегодня",
      addTaskInput: "что вы вырастите сегодня?",
      addTaskButton: "добaвить +",
      filterToday: "сегодня",
      filterAll: "все",
      filterActive: "активно",
      filterDone: "сделано",
      filterDeadlined: "просрочено",
      tasks: "задач",
      titleAllTasks: "Все задачи",
      titleActiveTasks: "Активные задачи",
      titleDoneTasks: "Сделанные задачи",
      titleDeadlinedTasks: "Просроченные задачи",
      titleTodayTasks: "На сегодня",
      noTasksMessage: "Задачи не найдены 🌱",
      deleteAllDoneTasksButton: "удалить сделанное",
      col1: "Статус",
      col2: "Задача",
      col3: "Категория",
      col5: "Удалить",
      switcherTable: "Показать таблицой",
      switcherGrid: "Показать сеткой",
      deadlineDate: "Дедлайн",
      createDate: "Создано",
      doneDate: "Выполнено",
      daysLeft: "осталось дней:",
      deadlinedDays: "просрочено на",
      days: "дней",
      more: "еще...",
    },
    settings: {
      title: "Настройки",
      profile: "ПРОФИЛЬ",
      hint1: "Нажмите на фото, чтобы загрузить новое",
      name: "Имя",
      save: "Сохранить изменения",
      styling: "ОФОРМЛЕНИЕ",
      light: "Светлая",
      dark: "Темная",
      account: "АККАУНТ",
      exitAcc: "Выйти из аккаунта",
      hint2: "Понадобится снова войти, чтобы увидеть свои задачи.",
      exit: "Выйти",
    },
    weather: {
      code1: "Ясно",
      code2: "Переменная облачность",
      code3: "Туман",
      code4: "Дождь",
      code5: "Снег",
      code6: "Ливень",
      code7: "Облачно",
      loading: "Загрузка погоды...",
      title1: "Бишкек",
      title2: "температура: ",
      title3: "на улице: ",
      error:'Нет прогноза'
    },
    calendar: {
      chosenDay: 'ВЫБРАННЫЙ ДЕНЬ',
    }
  },
};

export const i18n = createI18n({
  legacy: false,
  locale: "ru",
  fallbackLocale: "ru",
  messages: lang,
});
